#!/bin/sh
#cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
#. $WM_PROJECT_DIR/bin/tools/RunFunctions
nCORES=32


echo "---Reordering 0 folder---"
mv 0/ 0.mesh/
mv 0.run/ 0/

echo "---Running checkMesh---"
mpirun -n $nCORES checkMesh  -parallel -latestTime >log.checkMeshAnti 2>&1

echo "---Selecting only Region 0---"

#mpirun -n $nCORES splitMeshRegions -parallel -insidePoint '(2 0 0)'

mpirun -n $nCORES subsetMesh region0 -parallel -overwrite -noFields >log.subsetMesh 2>&1
#subsetMesh region0 -overwrite >log.subsetMesh 2>&1
#./AllmeshDelete

echo "---Running checkMesh---"
mpirun -n $nCORES checkMesh  -parallel -latestTime >log.checkMeshPost 2>&1
#checkMesh -latestTime >log.checkMesh2 2>&1
echo "---Reordering 0 folder---"
mv 0/ 0.run/
mv 0.mesh/ 0/

echo "---Running reconstructParMesh---"
reconstructParMesh -constant >log.reconstructParMesh 2>&1

#------------------------------------------------------------------------------
