#!/bin/sh
#cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

nCORES=32


#echo "---Running reconstructParMesh---"
reconstructParMesh -constant >log.reconstructParMesh 2>&1
#------------------------------------------------------------------------------
